### PR TITLE
feat(#591): Add Unit Tests for DirectivesAttribute and DirectivesAttributes

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
In this PR I added unit tests for `DirectivesAttribute` and `DirectivesAttributes` classes.

Closes: #591.
History:
- **feat(#591): add tests for DirectivesAttribute**
- **feat(#591): add unit tests for DirectivesAttributes**
- **feat(#591): remove outdated puzzles**
- **feat(#591): simplify DirectivesAttributes test**
- **feat(#591): fix all the code offences**

---

## PR-Codex overview
This PR adds unit tests for the `DirectivesAttribute` and `DirectivesAttributes` classes to increase code coverage and improve code quality.

### Detailed summary
- Added unit tests for `DirectivesAttribute` and `DirectivesAttributes` classes
- Improved code coverage and quality

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by 0crat** [comment]
@volodya-lombrozo Thanks for your contribution! Here's a breakdown of your +4 points reward: +4 base, +7 for 146 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html), -16 for no code review, -4 for only 2 comments, and +13 adjustment. Remember, code reviews and more comments can boost your score next time. [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) up the good work! Your balance is now [+89](https://www.eolang.org/zerocracy/objectionary-vitals.html).

**Comment by 0crat** [comment]
@volodya-lombrozo Hey there! 👋 Great job on your contribution! You've earned +4 points, which breaks down like this: +4 base points, +7 for your 146 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html), -16 because we missed the code review (oops!), -4 for only having 2 comments (we aim for at least 6), and +13 to keep you motivated. Remember, code reviews and comments are super important - they help us all improve! Your total balance is now [+89](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep the contributions coming and let's aim for more reviews and comments next time. [Quality and speed](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) go hand in hand!

**Comment by 0crat** [comment]
@volodya-lombrozo Hey there! 👋 Great job on your contribution! You've earned +4 points, which breaks down like this: +4 base, +7 for your 146 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html), -16 for no code review (oops!), -4 for only 2 comments, and +13 to keep you motivated. Remember, code reviews and comments are super important - they could boost your points next time! [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the contributions coming. Your balance is now [+89](https://www.eolang.org/zerocracy/objectionary-vitals.html). Let's aim for even better next time! 💪

**Comment by 0crat** [comment]
@volodya-lombrozo Hey there! 👋 Great work on your contribution! You've earned +4 points, which breaks down like this: +4 base points, +7 for your 146 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html), -16 because we missed the code review (oops!), -4 for only having 2 comments, and +13 to keep you motivated. Remember, code reviews and comments are super important - they help us all improve! Let's aim for at least 6 comments next time. [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the contributions coming! Your current balance is [+89](https://www.eolang.org/zerocracy/objectionary-vitals.html). Looking forward to your next awesome contribution! 🚀

**Comment by 0crat** [comment]
@volodya-lombrozo Hey there! 👋 Great job on your contribution! You've earned +4 points, which breaks down like this: +4 base points, +7 for your 146 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) (nice work!), -16 because we missed the code review (oops!), -4 for only having 2 comments (let's aim for 6+ next time), and +13 to keep you motivated. Remember, code reviews and comments are super important for our team's success. [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the contributions coming! Your current balance is [+89](https://www.eolang.org/zerocracy/objectionary-vitals.html). Let's crush it on the next one! 💪

**Comment by 0crat** [comment]
@volodya-lombrozo Great work on your contribution! 🌟 You've earned +4 points: +4 base, +7 for 146 hits-of-code, -16 for missed code review, -4 for minimal comments, and +13 bonus. Your effort is appreciated! [Keep the momentum](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) going. Your current balance stands at [+89](https://www.eolang.org/zerocracy/objectionary-vitals.html). Looking forward to your next contribution!

**Pull request merged**
