### PR TITLE
feat(#387): Rename goals `assemble/disassemble`

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Rename goals `bytecode-to-eo/eo-to-bytecode` -> `disassemble/assemble`.

Closes: #387
____
History:
- feat(#387): rename mojos
- feat(#387): use disassemble/assemble in integration tests
- feat(#387): update all docs related to goals naming

---

### Detailed summary
- Renamed the goals in the `pom.xml` files from `bytecode-to-eo` to `disassemble` and from `eo-to-bytecode` to `assemble`.
- Renamed the classes `BytecodeToEoMojo` to `DisassembleMojo` and `EoToBytecodeMojo` to `AssembleMojo`.
- Updated the documentation in `README.md` to reflect the changes in goal names.
- Added a reference to the `DisassembleMojo` class in `ImprovementEoFootprint.java`.

This PR focuses on renaming goals and classes related to the conversion of bytecode to EOlang and vice versa. It also updates the documentation to reflect the changes.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you review this one, please?

**Review by yegor256 — APPROVED** [review]
looks good

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.2.14`, title is `0.2.14`.

**Pull request merged**
