### PR TITLE
feat(#768): Verify All The Generated Bytecode

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
In this PR I changed the bytecode verification strategy. We used to verify each bytecode class on the fly, one by one, during the generation. 
Now we check the bytecode only when all the classes were assembled.
Reason: for the bytecode verification we need to know all the dependencies (classes) ahead of time.

This changes might help to avoid using of `skipVerification` flag in most cases.
Related to #768.

---

## PR-Codex overview
This PR focuses on refactoring the bytecode verification process, simplifying class constructors, and enhancing the `BytecodeDirectory` functionality. It removes unnecessary parameters and streamlines the verification logic.

### Detailed summary
- Moved `Parameter` class to `org.eolang.hone.param` package.
- Updated `JeoClassLoader` to use `JeoClassLoader.prestructor(classes)`.
- Simplified `Assembler` and `XmirRepresentations` constructors by removing `verify` parameter.
- Enhanced `BytecodeDirectory` with methods for bytecode verification.
- Removed unused verification logic and classes from `CustomClassWriter`.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you take a look, please?

**Comment by yegor256** [comment]
@volodya-lombrozo I don't see any new tests in this PR. What the change have been made for? What problem did you solve? Or it's just a refactoring? (I'm not sure it's true)

**Comment by volodya-lombrozo** [comment]
@yegor256 Thank you! I added the following configuration to one of the integration tests:

```xml
<!--
  We clean target/classes directory to be sure
  that bytecode verification works without old
  class files.
-->
<plugin>
  <artifactId>maven-clean-plugin</artifactId>
  <version>3.4.0</version>
  <executions>
    <execution>
      <id>clean target</id>
      <phase>process-classes</phase>
      <goals>
        <goal>clean</goal>
      </goals>
      <configuration>
        <excludeDefaultDirectories>true</excludeDefaultDirectories>
        <filesets>
          <fileset>
            <directory>target/classes</directory>
          </fileset>
        </filesets>
      </configuration>
    </execution>
  </executions>
</plugin>
```

(It removes `target/classes` folder) This behaviour emulates the exact situation you have [here](https://github.com/objectionary/jeo-maven-plugin/issues/768#issuecomment-2418706741). Without these changes the integration test fails.

**Comment by volodya-lombrozo** [comment]
@yegor256 can you have a look one more time, please?

**Review by yegor256 — APPROVED** [review]
@volodya-lombrozo LGTM

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Pull request merged**
