### PR TITLE
feat(#214): Correct Directory For Generated Sources

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Change output directory from `jeo/xmir` to `generated-sources/xmir`.

Closes: #214.
____
History:
- feat(#214): Change default directory from 'jeo/xmir' to 'generated-sources/xmir'
- feat(#214): fix all integration tests

---

## PR-Codex overview
This PR focuses on refactoring file paths in the codebase. 

### Detailed summary
- Updated file paths in multiple Java files from "jeo/xmir" to "xmir".
- Updated file paths in multiple Groovy test files from "jeo/xmir" to "xmir".
- Updated file paths in Maven plugin configuration files from "jeo/xmir" to "generated-sources/xmir".
- Updated file paths in the README.md file from "target/jeo" to "target/generated-sources".
- Updated file paths in Groovy test files from "target/jeo" to "target/generated-sources".

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Could you take a look, please?

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon reminder

**Review by maxonfjvipon — APPROVED** [review]
@volodya-lombrozo LGTM! Thanks

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Pull request merged**
