### PR TITLE
feat(#947): Disable XMIR Verification by Default

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
In this PR I disable XMIR verification by default for both goals `disassemble/assemble`.
Now, in order to enable it we need to use the following config:
```xml
<configuration>
  <xmirVerification>true</xmirVerification>
</configuration>
```

btw, the xmir verification is still active for the most of the integration tests. The only test, where it's disabled, is `spring-fat`.
We did it intentionally, because XMIR verification takes unreasonable amount of time. You can read more about this problem here:
https://github.com/objectionary/lints/issues/133

Closes: #947.

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you review these changes, please?

**Review by yegor256 — APPROVED** [review]
@volodya-lombrozo LGTM!

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by 0crat** [comment]
@volodya-lombrozo Thanks for the contribution! You've earned +4 points for this: +4 as a basis; -8 for too many hits-of-code (271 >= 200); -4 for very few (3) comments; +12 to give you at least something. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [-10](https://www.eolang.org/zerocracy/objectionary-vitals.html).

**Comment by 0crat** [comment]
@yegor256 Thanks for the review! You've earned +4 points for this: +4 as a basis; -10 for very few (4) comments; +10 to give you at least something.  Your running balance is [-24](https://www.eolang.org/zerocracy/objectionary-vitals.html).

**Pull request merged**
