### PR TITLE
feat(#889): Optimize Disassemble/Assemble Goals

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
In this PR I optimize `disassemble/assemle` goals to speed up development.

Timings after optimization:
```
[INFO]           spring-fat/pom.xml ............................... SUCCESS (301.7 s)
[INFO]           spring-fat/pom.xml ............................... SUCCESS (313.2 s)
[INFO]           spring-fat/pom.xml ............................... SUCCESS (378.5 s)
```

As you can see, in some cases we got ~ x10 speed up.

Related to #889.

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you review these changes, please? I guess, `eo` repository has the same problems as well. It might be interesting for you.

**Comment by yegor256** [comment]
@volodya-lombrozo looks good, but maybe it's better to fix the performance problem in the `com.jcabi.xml.XMLDocument` class?

**Comment by yegor256** [comment]
@volodya-lombrozo I can't understand where the performance gain is coming from? `XMLDocument` also encapsulates `Node` (not a String).

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo looks good, but maybe it's better to fix the performance problem in the `com.jcabi.xml.XMLDocument` class?

@yegor256 Sure, I left the ticket for it https://github.com/jcabi/jcabi-xml/issues/277

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo I can't understand where the performance gain is coming from? `XMLDocument` also encapsulates `Node` (not a String).

@yegor256 It's an open question, we need to investigate it separately.

**Comment by volodya-lombrozo** [comment]
@yegor256 Can I merge these changes?

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Pull request merged**
