### PR TITLE
feat(#710): Add `org.eolang` and `org.eolang.jeo` packages

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
In this PR I added support of FQN for all the generated objects. This involves adding of `org.eolang` and `org.eolang.jeo` packages to all the generated objects.

Closes: #710.
History:
- **feat(#710): add EoFqn and JeoFqn classes**
- **feat(#710): try to apply EoFqn and JeoFqn to all base attributes. All tests fail!**
- **feat(#710): fix most of the integration tests**
- **feat(#710): fix all the integration tests**
- **feat(#710): fix all the code offences**
- **feat(#710): add one more puzzle**

---

## PR-Codex overview
The focus of this PR is to update XML element base attributes to use fully qualified names in the EO language representation classes.

### Detailed summary
- Updated XML element base attributes to use fully qualified names
- Replaced hardcoded values with `JeoFqn` and `EoFqn` instances
- Improved consistency and readability in the codebase

> The following files were skipped due to too many changes: `src/main/java/org/eolang/jeo/representation/xmir/XmlTryCatchEntry.java`, `src/main/java/org/eolang/jeo/representation/xmir/XmlAttribute.java`, `src/test/java/org/eolang/jeo/representation/bytecode/BytecodeMethodParameterTest.java`, `src/main/java/org/eolang/jeo/representation/xmir/XmlClass.java`, `src/main/java/org/eolang/jeo/representation/xmir/XmlAnnotation.java`, `src/test/java/org/eolang/jeo/representation/xmir/XmlAttributeTest.java`, `src/test/java/org/eolang/jeo/representation/xmir/XmlAttributesTest.java`, `src/main/java/org/eolang/jeo/representation/xmir/XmlNode.java`, `src/main/java/org/eolang/jeo/representation/xmir/XmlOperand.java`, `src/test/java/org/eolang/jeo/representation/xmir/XmlInstructionTest.java`, `src/main/java/org/eolang/jeo/representation/DataType.java`, `src/test/java/org/eolang/jeo/representation/directives/DirectivesFieldTest.java`, `src/main/java/org/eolang/jeo/representation/xmir/XmlMethod.java`, `src/test/java/org/eolang/jeo/representation/directives/DirectivesClassTest.java`, `src/test/java/org/eolang/jeo/representation/xmir/XmlTryCatchEntryTest.java`, `src/main/java/org/eolang/jeo/representation/directives/DirectivesSeq.java`, `src/test/java/org/eolang/jeo/representation/directives/DirectivesClassPropertiesTest.java`, `src/test/java/org/eolang/jeo/representation/xmir/XmlFrameTest.java`, `src/test/java/org/eolang/jeo/representation/directives/DirectivesAnnotationPropertyTest.java`, `src/test/java/org/eolang/jeo/representation/directives/DirectivesAnnotationsTest.java`, `src/main/java/org/eolang/jeo/representation/directives/EoFqn.java`, `src/test/java/org/eolang/jeo/representation/directives/JeoFqnTest.java`, `src/it/fails-if-bytecode-broken/verify.groovy`, `src/main/java/org/eolang/jeo/representation/directives/JeoFqn.java`, `src/test/java/org/eolang/jeo/representation/directives/HasMethod.java`, `src/it/eo-to-bytecode/target/generated-sources/opeo-xmir/org/eolang/spring/WithoutMetas.xmir`, `src/it/eo-to-bytecode/target/generated-sources/opeo-xmir/org/eolang/benchmark/BA.xmir`, `src/test/resources/org/eolang/jeo/Application.xmir`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
Blocked by https://github.com/objectionary/eo/issues/3373#issuecomment-2358425399

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon This PR blocks other issues in this repository. Are the packages  `org.eolang` and `org.eolang.jeo` suitable for your needs (at least for now), or maybe you need some significant changes?

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo at least for now it's ok

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by 0crat** [comment]
@volodya-lombrozo Thanks for the contribution! You've earned +4 points for this: +4 as a basis; -8 for too many hits-of-code (1529 >= 200); -16 for way too many hits-of-code (1529 >= 800); -16 for the lack of code review; -4 for very few (5) comments; +44 to give you at least something. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+89](https://www.eolang.org/zerocracy/objectionary-vitals.html).

**Comment by 0crat** [comment]
@volodya-lombrozo Great work on your contribution! 🌟 You've earned +4 points, with adjustments for code volume and review. While there's room for improvement in code size and comments, we value your effort. Your [running balance](https://www.eolang.org/zerocracy/objectionary-vitals.html) is now +89. Keep the contributions coming and remember, [quality matters](https://www.yegor256.com/2018/03/06/speed-vs-quality.html)!

**Comment by 0crat** [comment]
@volodya-lombrozo Great work on your contribution! 🌟 You've earned +4 points, with adjustments for code volume and review. While there's room for improvement in code size and comments, we appreciate your effort. Your balance is now [+89](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep the contributions coming and check out this [article](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) for tips on balancing speed and quality!

**Comment by 0crat** [comment]
@volodya-lombrozo Thanks for your contribution! You've earned +4 points: +4 base, -8 for exceeding 200 hits-of-code (1529), -16 for surpassing 800 hits-of-code, -16 for no code review, -4 for only 5 comments, +44 adjustment. While the code volume is impressive, remember our policy values quality and review. Consider breaking larger contributions into smaller, reviewable chunks. Your balance is now [+89](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep [improving](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) and contributing!

**Comment by 0crat** [comment]
@volodya-lombrozo Great job on your contribution! 🌟 You've earned +4 points, with adjustments for code size and review. While there's room for improvement in code conciseness and comments, we value your effort. Your balance is now [+89](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the good work and remember to [focus on quality](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) in your next submission!

**Comment by 0crat** [comment]
@volodya-lombrozo Thank you for your contribution! We appreciate your effort, but there are some areas for improvement. Your submission of 1529 hits-of-code exceeds our guidelines, resulting in deductions. Additionally, the lack of code review and limited comments (5) have impacted your points. Despite these challenges, you've earned +4 points: +4 base, -24 for excess code, -16 for no review, -4 for few comments, +44 adjustment. Please focus on [quality over quantity](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) in future contributions. Your current balance is [+89](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the effort, and let's work on improving the review process!

**Comment by 0crat** [comment]
@volodya-lombrozo Hey there! 👋 Thanks for your contribution! Your effort is appreciated, but it seems we've got some room for improvement. You've earned +4 points, but there were a few hiccups: -8 for exceeding 200 hits-of-code (1529!), -16 for going over 800, -16 for missing code review, and -4 for only 5 comments. We had to add +44 to keep you at the minimum 4 points. Remember, [quality over quantity](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) is key! Aim for fewer hits-of-code and make sure to get those code reviews. Keep the contributions coming, and let's work on boosting that [+89](https://www.eolang.org/zerocracy/objectionary-vitals.html) balance! 💪

**Comment by 0crat** [comment]
@volodya-lombrozo Great work on your contribution! 🌟 You've earned +4 points, with adjustments for code volume and review. While there's room for improvement in code size and comments, we value your effort. Your balance is now [+89](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep the contributions coming and check out our [quality guidelines](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) for future submissions!

**Comment by 0crat** [comment]
@volodya-lombrozo Great contribution! Here's your reward breakdown: +4 base points, -8 for 1529 hits-of-code (≥200), -16 for exceeding 800 hits-of-code, -16 for no code review, -4 for only 5 comments. We've added +44 to ensure a minimum reward. Your total: +4 points. Remember, smaller, [quality contributions](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) with thorough reviews are ideal. Keep them coming! Your balance is now [+89](https://www.eolang.org/zerocracy/objectionary-vitals.html).

**Comment by 0crat** [comment]
@volodya-lombrozo Thanks for the contribution! You've earned +4 points for this: +4 as a basis; -8 for too many hits-of-code (1529 >= 200); -16 for way too many hits-of-code (1529 >= 800); -16 for the lack of code review; -4 for very few (5) comments; +44 to give you at least something. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+89](https://www.eolang.org/zerocracy/objectionary-vitals.html).

**Comment by 0crat** [comment]
@volodya-lombrozo Thanks for the contribution! You've earned +4 points for this: +4 as a basis; -8 for too many hits-of-code (1529 >= 200); -16 for way too many hits-of-code (1529 >= 800); -16 for the lack of code review; -4 for very few (5) comments; +44 to give you at least something. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+89](https://www.eolang.org/zerocracy/objectionary-vitals.html).

**Pull request merged**
