### PR TITLE
feat(#635): Remove `@line` Attribute

### LINKED ISSUE #635: DirectivesData.java:37-42: Remove 'line' attribute...
The puzzle `627-fdafed58` from #627 has to be resolved: 

https://github.com/objectionary/jeo-maven-plugin/blob/9b9d6def708c449602362df465ec7f9c08a635bf/src/main/java/org/eolang/jeo/representation/directives/DirectivesData.java#L37-L42

The puzzle was created by rultor on 07-Jul-24. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
In this PR I remove outdated `@line` attribute from `XMIR` and upgraded eo up to the `0.44.0` version.

Closes #635.

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Suddenly, I can't remove `@line` attribute, because the following error:

```
[ERROR] Failed to execute goal org.eolang:eo-maven-plugin:0.43.2:xmir-to-phi (convert-xmir-to-eo) on project jeo-it: 'PhiMojo' execution failed: java.io.UncheckedIOException: java.io.IOException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Shift 'com.yegor256.xsline.StLogged@2cc65825' failed: Shift 'com.yegor256.xsline.StClasspath@7bfe9db5' failed: Failed to transform by net.sf.saxon.jaxp.TransformerImpl: Processing terminated by xsl:message at line 79 in add-refs.xsl; SystemID: file:///org/eolang/parser/add-refs.xsl; Line#: 79; Column#: 40 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eolang:eo-maven-plugin:0.43.2:xmir-to-phi (convert-xmir-to-eo) on project jeo-it: 'PhiMojo' execution failed
```

Seems, that removing `line` attribute from `XSD` isn't sufficient to remove it from `jeo-maven-plugin`

**Comment by yegor256** [comment]
@volodya-lombrozo please, show the full log. In your message, I don't see the error text reported by `add-refs.xsl`.

**Comment by volodya-lombrozo** [comment]
@yegor256 Here is the full log:
[build.log](https://github.com/user-attachments/files/17956283/build.log)

**Comment by yegor256** [comment]
@volodya-lombrozo let's try again, when we release eo 0.44.0

**Comment by volodya-lombrozo** [comment]
@yegor256 ok, I'm waiting for it

**Review by yegor256 — APPROVED** [review]
@volodya-lombrozo LGTM

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Pull request merged**
