### PR TITLE
feat(#705): Append Docs About Unrolling

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
In this PR I try to explain why we can't apply `unrolling` for all the files generated by `jeo`. 
We need to apply "unrolling" only when we applied `phi/unphi` transformations. 
I added an integration test that demonstrates the correct usage.

Also in this PR I fixed several small refactoring issues.

Related to #705.

---

## PR-Codex overview
This PR focuses on refactoring and improving the handling of XMIR files in the `phi/unphi` transformation process. It enhances the structure and readability of the code, introduces a new `Unroller` class, and updates documentation.

### Detailed summary
- Renamed execution id in `pom.xml` from `uroll-phi` to `unroll-phi`.
- Simplified logic in `XmlOperand.java` for parsing XML bytes.
- Added a constructor to `CanonicalXmir` with documentation.
- Enhanced `DirectivesTypedValue` with `@ToString` and `@EqualsAndHashCode` annotations.
- Updated README.md with a short explanation of the integration test steps.
- Refactored `UnrollMojo` to use a new `Unroller` class for unrolling XMIR files.
- Introduced `Unroller` class to handle unrolling logic, including methods for processing XMIR files and checking file types.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you review this changes, please? They might help you with the **hone** pipeline configuration.

**Comment by volodya-lombrozo** [comment]
@yegor256 Reminder

**Review by yegor256 — APPROVED** [review]
@volodya-lombrozo LGTM

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by 0crat** [comment]
@volodya-lombrozo Great work on your contribution! 🌟 You've earned +4 points: +4 base, -8 for exceeding code limit (239 >= 200), -4 for limited comments (4), +12 bonus. Your effort is appreciated! [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) up the good work. Your current balance: [+101](https://www.eolang.org/zerocracy/objectionary-vitals.html). Looking forward to your next contribution!

**Comment by 0crat** [comment]
@yegor256 Thank you for your code review contribution! We appreciate your effort, but there's room for improvement. Based on our policy, you've earned +4 points as a base reward. However, we had to deduct 10 points due to the low number of comments (5). To ensure a minimum reward, we've added 10 points, resulting in a total of +4 points for this review. Your current balance stands at [-71](https://www.eolang.org/zerocracy/objectionary-vitals.html). We encourage you to provide more detailed feedback in future reviews to maximize your rewards and enhance our code quality. Keep up the good work! 💻👍

**Pull request merged**
